<?php /** @var FirmsModel $model */ ?>
<?php /** @var FirmsView $view */ ?>

<?php $top_image = $model->firm_data['images']['top'] ?? ''; ?>
<?php $background_image = $model->firm_data['images']['background'] ?? ''; ?>

    <div class="btnUp"><img src="/prod_src/img/firms/up.svg" alt=""/></div>

    <header class="firmMenuSticky">

        <div class="firmMenuContainer">

            <?php if ($model->firm_data['logo']) { ?>
                <div class="firmMenuImg">
                    <img src="<?php echo $model->firm_data['logo']; ?>" title="<?php echo $model->firm_data['name']; ?>"
                         alt="<?php echo $model->firm_data['name']; ?>"/>
                </div>
            <?php } ?>

            <div>
                <div class="firmMenuContainer">
                    <div class="firmMenuText">
                        <div class="firstHeader">
                            <?php echo $model->firm_data['firm_name_only']; ?>
                        </div>
                    </div>
                </div>
                <div class="firmMenuContainer">
                    <div class="firmMenuItems">
                        <?php echo $view->menu->setAttributes()->render(); ?>
                    </div>
                </div>
            </div>
        </div>
    </header>

    <div class="mnuHelpContainer">
        <section class="firmMenu">
            <div class="grey-line">
                <div class="firmMenuContainer">
                    <div>
                        <div class="firmMenuContainer flex-row-between-center">
                            <div class="addInfo_mnp">
                                <div class="firmMenuText">
                                <span class="firstHeaderMonopolist">
                                    <?php echo $model->firm_data['firm_name_only']; ?>
                                </span>
                                    <p class="firmRubric firmDescription">
                                        <?php echo $model->firm_data['firm_description']; ?>
                                    <p>
                                </div>
                                <div class="firmInfoMnpBox">
                                    <div class="firmInfoBox_el">
                                        <p>
                                            <?php echo $model->firm_data['address_abbreviated'] ?? $model->firm_data['address']; ?>
                                        </p>
                                        <p class="firm_phone">
                                            <a href="tel:<?php echo $model->firm_data['main_telephone_clean']; ?>">
                                                <?php echo $model->firm_data['main_telephone']; ?>
                                            </a>
                                        </p>
                                    </div>
                                    <?php if ($model->firm_data['has_work_times']) { ?>
                                        <div class="firmInfoBox_el">
                                            <?php if ($model->firm_data['is_open_today']) { ?>
                                                <div class="open">Открыто</div>
                                            <?php } else { ?>
                                                <div class="close">Закрыто</div>
                                            <?php } ?>

                                            <?php foreach ($model->work_times as $work_time) { ?>
                                                <p><?php echo $work_time['text']; ?></p>
                                            <?php } ?>
                                        </div>
                                    <?php } ?>
                                </div>
                                <div class="box-btn">
                                    <?php if (count($model->firm_data['firm_sites']) > 0) { ?>
                                        <?php $firm_site = reset($model->firm_data['firm_sites']); ?>
                                        <a onclick="<?php echo $firm_site['onclick']; ?>"
                                           title="<?php echo $firm_site['title']; ?>" class="site-btn">
                                            <?php echo $firm_site['site']; ?>
                                        </a>
                                    <?php } ?>

                                    <?php if (count($model->firm_data['filtered_social_networks']) > 0) { ?>
                                        <div class="firm-soc-ntw">
                                            <?php foreach ($model->firm_data['filtered_social_networks'] as $network => $social_network) { ?>
                                                <a href="//<?php echo $social_network['url']; ?>" class="soc-ntw-btn">
                                                    <img src="/prod_src/img/firms/firm/monopolist/social_networks/<?php echo $network ?>.png"
                                                         alt="<?php echo $network ?>" title="<?php echo $network ?>"/>
                                                </a>
                                            <?php } ?>
                                        </div>
                                    <?php } ?>
                                </div>

                                <?php if (!empty($model->firm_data['partner_button_content'])) { ?>
                                    <a class="actionBtn btn_show_more">
                                        <span onclick="<?php echo $model->firm_data['partner_button_content']['onclick']; ?>">
                                            <?php echo $model->firm_data['partner_button_content']['text']; ?>
                                        </span>
                                        <img src="/prod_src/img/firms/opinions/arrow-point-to-right.png" width="7px"
                                             height="12px"
                                             alt="<?php echo $model->firm_data['partner_button_content']['text']; ?>"/>
                                    </a>
                                <?php } ?>
                            </div>
                            <div class="fismSpecPhoto">
                                <?php if (!empty($top_image)) { ?>
                                    <img src="<?php echo $top_image; ?>"/>
                                <?php } ?>
                            </div>
                        </div>
                        <div class="greyMenuSection">
                            <div class="firmMenuContainer">
                                <div class="firmMenuItems">
                                    <?php echo $view->menu->setAttributes(['id' => 'owl-firmMenu', 'class' => 'owl-carousel'])->render(); ?>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </div>
<?php if (!empty($background_image)) { ?>
    <style>
        .firstSectionMonopolist:before {
            background-image: url(<?php echo $background_image; ?>)
        }
    </style>
<?php } ?>