<?php

/* @var $model AboutModel */
/* @var $view AboutView */

?>

<div id="main_wrap">

    <div class="ineer_wrap">

        <div class="sidebar">

            <a href="/about/mission" class="button">Наша миссия</a>
            <a href="/about/contacts" class="button">Контакты</a>
            <a href="/about/production" class="button">Продукция и услуги</a>
            <a href="/about/feedback" class="button">Написать нам</a>

        </div>

        <div id="main_text" class="inner_content">

            <hr>

                Вы можете отправить нам письмо по адресу: <a href="mailto:info@georostgrupp.ru">info@georostgrupp.ru</a>
                <br>
                Или воспользуйтесь формой обратной связи:

                <br>
                <br>

                <form id="feedbackform" action="/about/feedback?send=1" method="post">
                    <label for="fio" style="font-weight: 800">Ваше ФИО:</label>
                    <br>
                    <input style="width: 95%;font-size: 16px;" id="forfio" name="fio" value="">
                    <br>

                    <label for="message" style="font-weight: 800">Сообщение:</label>
                    <br>
                    <textarea style="width: 95%;height: 100px;font-size: 16px;" id="formessage" name="message" value=""></textarea>
                    <br>
                    <label for="fio" style="font-weight: 800">Символы с картинки:</label>
                    <br>
                    <input style="height:30px;width: 100px;font-size: 16px;" id="forcaptcha" name="captcha" value="">
                    <img src="/public/prod_src/img/captcha/test.jpg">

                    <input style="display:none;" id="forcheck" name="check" value="<?php echo md5(date('H-m-s'));?>">

                    <input class="button" type="submit" value="Отправить"/>
                    <?php if ($model->feedback_status == -1) {?>
                        <br>
                        <span style="color:#f00;font-size:16px;font-weight: 700">Ошибка. Проверьте заполненность всех полей.</span>
                        <br>
                    <?php }?>

                    <?php if ($model->feedback_status == 1) {?>
                        <br>
                        <span style="color:#080;font-size:16px;font-weight: 700">Сообщение отправлено.</span>
                        <br>
                    <?php }?>
                </form>

            <hr>

        </div>

    </div>
</div>