<?php

/* @var $model AboutModel */
/* @var $view AboutView */

?>

<div id="main_wrap">

    <div class="ineer_wrap">

        <div class="sidebar">

            <a href="/about/mission" class="button">Наша миссия</a>
            <a href="/about/management" class="button active">Руководство</a>
            <a href="/about/contacts" class="button">Контакты</a>
            <a href="/about/production" class="button">Продукция и услуги</a>

        </div>

        <div id="main_text" class="inner_content">

            <hr>

            <p class="content_missing">
                Сайт находится на наполнении
            </p>

            <hr>

        </div>

    </div>
</div>