<?php

/* @var $model AboutModel */
/* @var $view AboutView */

?>

<div id="main_wrap">

    <div class="ineer_wrap">

        <div class="sidebar">

            <a href="/about/mission" class="button active">Наша миссия</a>
            <a href="/about/contacts" class="button">Контакты</a>
            <a href="/about/production" class="button">Продукция и услуги</a>
            <a href="/about/feedback" class="button">Написать нам</a>

        </div>

        <div id="main_text" class="inner_content">

            <hr>

            <p>
                <b style="font-size:22px;">Миссия компании</b> — создание уникальных производств, Экотехнопарков и реализация мероприятий в рамках импортозамещения.
            </p>

            <h3>Цели и ценности:</h3>

            <ul class="list">
                <li>создание и эксплуатация уникальных производств;</li>
                <li>повышение конкурентноспособности отечественной промышленности;</li>
                <li>экономическое развитие территории Республики Башкортостан;</li>
                <li>повышение уровня и качества жизни населения.</li>
            </ul>

            <hr>

        </div>

    </div>
</div>