<?php

/* @var $model AboutModel */
/* @var $view AboutView */

?>

<div id="main_wrap">

    <div class="ineer_wrap">

        <div class="sidebar">

            <a href="/about/mission" class="button">Наша миссия</a>
            <a href="/about/contacts" class="button">Контакты</a>
            <a href="/about/production" class="button active">Продукция и услуги</a>
            <a href="/about/feedback" class="button">Написать нам</a>

        </div>

        <div id="main_text" class="inner_content">

            <hr>

            <h3>Продукция и услуги.</h3>

            <p>ООО «ГеоРостГрупп» предлагает заинтересованным лицам и организациям следующие услуги:</p>
            <ul class="list">
                <li>формирование инвестиционных проектов с использованием инновационных разработок и НОУ-ХАУ;</li>
                <li>содействие в подготовке предпроектной и проектной документации;</li>
                <li>бизнес-планирование;</li>
                <li>подбор технологических партнеров;</li>
                <li>подбор поставщиков оборудования;</li>
                <li>подбор наилучших, доступных технологий;</li>
                <li>доверительное управление имуществом.</li>
            </ul>

            <hr>

        </div>

    </div>
</div>