<?php

/* @var $model AboutModel */
/* @var $view AboutView */

?>

<div id="main_wrap">

    <div class="ineer_wrap">

        <div class="sidebar">

            <a href="/about/mission" class="button">Наша миссия</a>
            <a href="/about/management" class="button">Руководство</a>
            <a href="/about/contacts" class="button">Контакты</a>
            <a href="/about/production" class="button active">Продукция и услуги</a>

        </div>

        <div id="main_text" class="inner_content">

            <hr>

            <h3>В рамках реализации проекта индустриального парка мы предлагаем следующие услуги:</h3>

            <ul class="list">
                <li>доверительное управление имуществом</li>
                <li>формирование инвестиционных проектов с использованием инновационных разработок</li>
                <li>содействие в подготовке предпроектной и проектной документации</li>
                <li>выбор поставщиков оборудования, логистика</li>
                <li>помощь в установлении прямых контактов с предприятиями Китая</li>
            </ul>


            <hr>

        </div>

    </div>
</div>