<?php
/* @var $model CommonModel */
/* @var $view CommonView */
?>


<header>

    <div class="menu-burger__header">
        <span></span>
    </div>

    <nav class="header__nav">

        <div class="logoMobCont">
        <div id="logo">
            <a href="/">
                <img src="/public/prod_src/img/logo_ru.png"/>
            </a>
        </div>
    </div>

        <ul class="menu header__menu">
            <li><a href="/" class="menu__itemn button<?php echo (Application::$application_name == 'Home' ? ' active' : ''); ?>">Главная</a></li>
            <li>
                <a href="/about" class="button<?php echo (Application::$application_name == 'About' ? ' active' : ''); ?>">О компании</a>
                <ul>
                    <li><a href="/" class="menu__itemn button<?php echo (Application::$application_name == 'Home' ? ' active' : ''); ?>">Главная</a></li>
                    <li><a href="/" class="menu__itemn button<?php echo (Application::$application_name == 'Home' ? ' active' : ''); ?>">Главная</a></li>
                </ul>
            </li>
            <li><a href="/documents" class="button<?php echo (Application::$application_name == 'Documents' ? ' active' : ''); ?>">Документация</a></li>
        </ul>
    </nav>

</header>








