<header class="firmMenuSticky">

    <div class="firmMenuContainer">

        <?php if ($model->firm_data['FIRM_LOGO']) { ?>
            <div class="firmMenuImg">
                <img src="<?php echo $model->firm_data['FIRM_LOGO']; ?>" alt=""/>
            </div>
        <?php } ?>

        <div>
            <div class="firmMenuContainer">
                <div class="firmMenuText">
                    <div class="firstHeader"><?php echo $model->firm_data['FIRMNAME_ONLY']; ?></div>
                </div>
            </div>
            <div class="firmMenuContainer">
                <div class="firmMenuItems">
                    <ul>

                        <li<?php if ($view->firm_menu_active == 'firms' || $view->firm_menu_active == 'map') { ?> class="firmMenuActive"<?php } ?>>
                            <?php if ($view->firm_menu_active != 'firms') { ?>
                            <a href="<?php echo $model->firm_data['firm_url']; ?>">
                                <?php } ?>
                                <span class="spanMenuText">Контакты</span>
                                <?php if ($view->firm_menu_active != 'firms') { ?>
                            </a>
                        <?php } ?>
                        </li>

                        <li<?php if ($view->firm_menu_active == 'prices') { ?> class="firmMenuActive"<?php } ?>>
                            <?php if ($view->firm_menu_active != 'prices' && $model->firm_data['firm_price_url']) { ?>
                            <a href="<?php echo $model->firm_data['firm_price_url']; ?>">
                                <?php } ?>
                                <?php if (!$model->firm_data['firm_price_url']) { ?>
                                <span class="nonActiveMenuItem" style="color: #999;">
                            <?php } ?>
                                    <span class="spanMenuText">Цены
                                        <?php if ($model->firm_data['count_prices']) { ?>
                                            <span class="firmMenuCount">
                                                <?php echo $model->firm_data['count_prices']; ?>
                                            </span>
                                        <?php } ?>
                                    </span>
                                    <?php if (!$model->firm_data['firm_price_url']) { ?>
                                </span>
                            <?php } ?>
                                <?php if ($view->firm_menu_active != 'prices') { ?>
                            </a>
                        <?php } ?>
                        </li>

                        <li<?php if ($view->firm_menu_active == 'opinions') { ?> class="firmMenuActive"<?php } ?>>

                            <?php if ($view->firm_menu_active != 'opinions' && $model->firm_data['URL_OTZYVY_FIRM']) { ?>

                            <a href="<?php echo $model->firm_data['URL_OTZYVY_FIRM']; ?>">

                                <?php } ?>

                                <span class="spanMenuText">Отзывы</span>

                                <?php if ($model->firm_data['opinions_count'] > 0) { ?>
                                    <span class="firmMenuCount">
                                    <span class="positiveOpinionsQuantity">
                                        <?php echo $model->firm_data['opinions_pros_count'] . ' : ' ?>
                                    </span>
                                    <span class="negativeOpinionsQuantity">
                                        <?php echo $model->firm_data['opinions_cons_count'] ?>
                                    </span>
                                </span>
                                <?php } ?>

                                <?php if ($view->firm_menu_active != 'opinions' && $model->firm_data['URL_OTZYVY_FIRM']) { ?>
                            </a>
                        <?php } ?>
                        </li>

                        <?php if (!empty($model->firm_data['FIRMA_DISCOUNT_URL'])) { ?>
                            <li class="<?php echo($view->firm_menu_active === 'discounts' ? 'firmMenuActive' : ''); ?>">
                                <?php
                                $text_url = '<span class="spanMenuText">Скидки и акции</span>';

                                if ($model->firm_data['discounts_count'] > 0) {
                                    $text_url .= '<span class="firmMenuCount">' . $model->firm_data['discounts_count'] . '</span>';
                                }
                                ?>

                                <?php if ($view->firm_menu_active !== 'discounts') { ?>
                                    <a href="<?php echo $model->firm_data['FIRMA_DISCOUNT_URL']; ?>"><?php echo $text_url; ?></a>
                                <?php } else { ?>
                                    <span><?php echo $text_url; ?></span>
                                <?php } ?>
                            </li>
                        <?php } ?>

                        <li<?php if ($view->firm_menu_active == 'stories') { ?> class="firmMenuActive"<?php } ?>>
                            <?php if ($view->firm_menu_active != 'stories' && $model->firm_data['FIRMA_VIDEO_URL']) { ?>
                                <a href="<?php echo $model->firm_data['FIRMA_VIDEO_URL']; ?>">Сюжеты
                                    <?php if ($model->firm_data['stories_count']) {
                                        echo $model->firm_data['stories_count'];
                                    } ?>
                                </a>
                            <?php } else { ?>
                                <span class="nonActiveMenuItem" style="color: #999;">Сюжеты</span>
                            <?php } ?>
                        </li>

                        <!-- Map item -->
                        <?php $is_active_map_item = $view->firm_menu_active === 'address'; ?>

                        <li class="<?php echo $is_active_map_item ? 'firmMenuActive' : ''; ?>">
                            <?php $map_url_text = '<span class="spanMenuText">Схема проезда</span>'; ?>
                            <?php if ($is_active_map_item) { ?>
                                <?php echo $map_url_text; ?>
                            <?php } else { ?>
                                <a href="<?php echo $model->firm_data['FIRMA_MAP_URL']; ?>">
                                    <?php echo $map_url_text; ?>
                                </a>
                            <?php } ?>
                        </li>

                        <?php if ($model->firm_data['URL_SETI_MAPS']) { ?>
                            <li class="<?php echo $view->firm_menu_active === 'division' ? 'firmMenuActive' : '' ?>">
                                <a href="<?php echo $model->firm_data['URL_SETI_MAPS']; ?>">
                                    Филиалы
                                    <?php if ($model->firm_data['net_filials_count']) { ?>
                                        <span class="firmMenuCount">
                                            <?php echo $model->firm_data['net_filials_count']; ?>
                                        </span>
                                    <?php } ?>
                                </a>
                            </li>
                        <?php } ?>

                    </ul>
                </div>
            </div>
        </div>
    </div>

</header>