<?php
/* @var DivisionModel $model */
/* @var DivisionView $view */
?>

<div class="btnUp">
    <img src="/prod_src/img/firms/up.svg" alt=""/>
</div>

<header class="firmMenuSticky">

    <div class="firmMenuContainer">

        <?php if ($model->net_data['logo_net']) { ?>
            <div class="firmMenuImg">
                <img src="<?php echo $model->net_data['logo_net'] ?>"
                     title="<?php echo $model->net_data['name_net'] ?>"
                     alt="<?php echo $model->net_data['name_net'] ?>"/>
            </div>
        <?php } ?>

        <div>
            <div class="firmMenuContainer">
                <div class="firmMenuText">
                    <div class="firstHeader"><?php echo $model->net_data['name_net']; ?></div>
                </div>
            </div>
            <div class="firmMenuContainer">
                <div class="firmMenuItems">
                    <ul>
                        <li>
                            <a href="<?php echo $model->net_opinions_url; ?>">Отзывы
                                <div class="firmMenuCount">
                                    <span class="positiveOpinionsQuantity">
                                        <?php echo $model->net_data['net_opinions_pros_count']; ?>
                                    </span>
                                    <span class="colon">: </span>
                                    <span class="negativeOpinionsQuantity">
                                        <?php echo $model->net_data['net_opinions_cons_count']; ?>
                                    </span>
                                </div>
                            </a>
                        </li>
                        <li class="firmMenuActive">Филиалы
                            <?php if ($model->firm_count) { ?>
                                <span class="firmMenuCount">
                                    <?php echo $model->firm_count ?>
                                 </span>
                            <?php } ?>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>

</header>

<div class="mnuHelpContainer">
    <section class="firmMenu">
        <div class="grey-line">
            <div class="firmMenuContainer">

                <div>
                    <div class="firmMenuContainer">
                        <div class="firmMenuText">
                            <span class="firstHeader">
                                <?php echo $model->net_data['name_net']; ?>
                            </span>
                            <p class="underHeader">
                                <?php if ($model->firm_count) { ?>
                                    <?php echo $model->firm_count_text ?>
                                <?php } ?>
                            </p>
                        </div>
                    </div>

                    <div class="greyMenuSection">
                        <div class="firmMenuContainer">
                            <div class="firmMenuItems">
                                <ul id="owl-firmMenu" class="owl-carousel">
                                    <li>
                                        <a href="<?php echo $model->net_opinions_url; ?>">Отзывы
                                            <div class="firmMenuCount">
                                                <span class="positiveOpinionsQuantity">
                                                    <?php echo $model->net_data['net_opinions_pros_count']; ?>
                                                </span>
                                                <span class="colon">: </span>
                                                <span class="negativeOpinionsQuantity">
                                                    <?php echo $model->net_data['net_opinions_cons_count']; ?>
                                                </span>
                                            </div>
                                        </a>
                                    </li>
                                    <li class="firmMenuActive">Филиалы
                                        <?php if ($model->firm_count) { ?>
                                            <span class="firmMenuCount">
                                                <?php echo $model->firm_count ?>
                                             </span>
                                        <?php } ?>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
</div>