<?php
/* @var $model StatisticsModel */
/* @var $view Statisticsview */
?>

<header class="firmMenuSticky">

    <div class="firmMenuContainer">

        <div>
            <div class="firmMenuContainer">
                <div class="firmMenuText">
                    <div class="firstHeader">Статистика посещаемости <?php echo Application::$model->empty_page_data['region']; ?></div>
                </div>
            </div>
            <div class="firmMenuContainer">
                <div class="firmMenuItems">
                    <ul>
                        <li class="firmMenuActive">
                            <span class="spanMenuText">Посещаемость городов</span>
                        </li>
                        <li>
                            <a href="#visits_table_rubr">Посещаемость разделов</a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>

</header>

<div class="mnuHelpContainer">
    <section class="firmMenu">
        <div class="grey-line">
            <div class="firmMenuContainer">
                <div>
                    <div class="firmMenuContainer">
                        <div class="firmMenuText">
                            <span class="firstHeader">Статистика посещаемости <?php echo Application::$model->empty_page_data['region']; ?></span>
                            <div class="firmLocation">
                                <img src="/prod_src/img/firms/location.svg" alt="">
                                <div class="firmAddress">
                                    <span id="copyText">
                                        <?php echo $model->okrug_list[ApplicationData::getData('id_okrug')]['name_1']; ?>
                                    </span>
                                    <div class="pseudoSelect">

                                        <p>Регионы РФ</p>

                                        <?php foreach ($model->okrug_list as $id_okrug => $okrug_data) { ?>

                                            <?php if (!empty($okrug_data['id_strana'])) {

                                                break;
                                            } ?>

                                            <a href="<?php echo '//' . $okrug_data['url'] . '/statistics'; ?>"<?php echo (Application::$base_domain_short == $okrug_data['url'] ? ' class="selected"' : ''); ?>>
                                                <?php echo $okrug_data['name_1']; ?>
                                            </a>

                                        <?php } ?>

                                        <p>Другие страны</p>

                                        <?php foreach ($model->okrug_list as $id_okrug => $okrug_data) { ?>

                                            <?php if (empty($okrug_data['id_strana'])) {

                                                continue;
                                            } ?>

                                            <a href="<?php echo '//' . $okrug_data['url'] . '/statistics'; ?>"<?php echo (Application::$base_domain_short == $okrug_data['url'] ? ' class="selected"' : ''); ?>>
                                                <?php echo $okrug_data['name_1']; ?>
                                            </a>

                                        <?php } ?>

                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="greyMenuSection">
                        <div class="firmMenuContainer">
                            <div class="firmMenuItems">
                                <ul id="owl-firmMenu" class="owl-carousel">
                                    <li class="firmMenuActive">
                                        <span class="spanMenuText">Посещаемость городов</span>
                                    </li>
                                    <li>
                                        <a href="#visits_table_rubr">Посещаемость разделов</a>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
</div>
