<?php
/* @var $model FirmsModel */
/* @var $view FirmsView */
?>

<div class="mnuHelpContainer">
    <section class="firmMenu">
        <div class="grey-line">
            <div class="firmMenuContainer">
                <div>
                    <div class="firmMenuContainer">
                        <div class="firmMenuText">
                            <span class="firstHeader">Добавить организацию</span>
                        </div>
                    </div>
                    <div class="greyMenuSection">
                        <div class="firmMenuContainer">
                            <div class="firmMenuItems">

                                <ul id="owl-firmMenu" class="owl-carousel">
                                    <li class="<?php echo (Application::$action == 'addFirm' ? 'firmMenuActive' : ''); ?>">

                                        <?php if (Application::$action == 'addFirm') {?>
                                            <span class="spanMenuText">Добавить организацию</span>
                                        <?php } else { ?>
                                            <a href="<?php echo Application::$base_domain . 'firms?action=addFirm'; ?>">Добавить организацию</a>
                                        <?php } ?>


                                    </li>
                                    <li class="<?php echo (Application::$action == 'addDivisions' ? 'firmMenuActive' : ''); ?>">

                                        <?php if (Application::$action == 'addDivisions') {?>
                                            <span class="spanMenuText">Добавить филиалы сети</span>
                                        <?php } else { ?>
                                            <a href="<?php echo Application::$base_domain . 'firms?action=addDivisions'; ?>">Добавить филиалы сети</a>
                                        <?php } ?>

                                    </li>
                                </ul>

                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
</div>
