<?php

/* @var $model AboutModel */
/* @var $view AboutView */

?>

<div id="main_wrap">

    <div class="ineer_wrap">

        <div class="sidebar" id="sidebar_nav_buttons">

            <a href="/documents/foundation" class="button" style="width: 186px">Учредительные документы</a>
            <a href="/documents/presentations" class="button" style="width: 186px">Презентации</a>

        </div>

        <div id="main_text" class="inner_content">

            <hr>

            <p class="content_missing">
                Учредительные документы высылаются по запросу.
            </p>

            <hr>

        </div>

    </div>
</div>