<?php

/* @var $model AboutModel */
/* @var $view AboutView */

?>

<div id="main_wrap">

    <div class="ineer_wrap">

        <div class="sidebar">

            <a href="/documents/foundation" class="button">Учредительные документы</a>
            <a href="/documents/presentations" class="button">Презентации</a>
            <a href="/documents/trend" class="button active">Направление развития</a>

        </div>

        <div id="main_text" class="inner_content">

            <hr>

            <p class="content_missing">
                Сайт находится на наполнении
            </p>

            <hr>

        </div>

    </div>
</div>