<?php
/* @var $model Application::$model */
?>

<div class="sectionBreadcrumbs">
    <div class="breadcrumbsCont">

        <div class="desStCont">
            <ul class="breadcrumbsStat <?php echo $view->breadcrumbs_css_class ?? ''; ?>">
                <?php foreach ($model->breadcrumbs as $link) { ?>
                    <?php if ($link['active']) { ?>
                        <li class="breadcrumbsItem">
                            <span class="activeBreadcrumb"><?php echo $link['name']; ?></span>
                        </li>
                    <?php } else { ?>
                        <li class="breadcrumbsItem">
                            <a href="<?php echo $link['url']; ?>"><?php echo $link['name']; ?></a>
                            <span class="breadcrumbsArrow">&mdash;</span>
                        </li>
                    <?php } ?>
                <?php } ?>
            </ul>
        </div>

        <div class="desStContMob">
            <div class="menuCont">
                <div class="burgerBtn">
                    <span class="one"></span><span class="two"></span><span class="three"></span>
                </div>
                <span class="menuSpan"></span>
            </div>

            <ul class="breadcrumbsStat" id="breadcrumbsStat">
                <?php foreach ($model->breadcrumbs as $link) { ?>
                    <?php if ($link['active']) { ?>
                        <li class="breadcrumbsItem">
                            <span class="activeBreadcrumb"><?php echo $link['name']; ?></span>
                        </li>
                    <?php } else { ?>
                        <li class="breadcrumbsItem">
                            <a href="<?php echo $link['url']; ?>"><?php echo $link['name']; ?></a>
                            <span class="breadcrumbsArrow">
                                <i class="fa fa-angle-right" aria-hidden="true"></i>
                            </span>
                        </li>
                    <?php } ?>
                <?php } ?>
            </ul>
        </div>
    </div>
</div>