<?php

/* @var $model AboutModel */
/* @var $view AboutView */

?>

<div id="main_wrap">

    <div class="ineer_wrap">

        <div class="sidebar">

            <a href="/park/focus" class="button active">Отраслевой фокус</a>
            <a href="/park/news" class="button">Новости</a>
            <a href="/park/partners" class="button">Партнеры</a>

        </div>

        <div id="main_text" class="inner_content">

            <hr>

            <h3>Отраслевой фокус</h3>

            <div class="focus_list">
                <img src="/public/prod_src/img/swipper/img_0.jpg">
                <p>Обработка, утилизация и обезвреживание отходов</p>
                <div class="clear"></div>
            </div>

            <div class="focus_list">
                <img src="/public/prod_src/img/swipper/img_2.jpg">
                <p>Металлургия, порошковая металлургия</p>
                <div class="clear"></div>
            </div>

            <div class="focus_list">
                <img src="/public/prod_src/img/swipper/img_4.jpg">
                <p>Производство оборудования для нефтегазовой промышленности</p>
                <div class="clear"></div>
            </div>

            <div class="focus_list">
                <img src="/public/prod_src/img/swipper/img_5.jpg">
                <p>Приборостроение</p>
                <div class="clear"></div>
            </div>

            <div class="focus_list">
                <img src="/public/prod_src/img/swipper/img_3.jpg">
                <p>Металлообрабатывающая промышленность</p>
                <div class="clear"></div>
            </div>

            <div class="focus_list">
                <img src="/public/prod_src/img/swipper/img_1.jpg">
                <p>Информационные технологии</p>
                <div class="clear"></div>
            </div>

            <hr>

        </div>

    </div>
</div>