<?php

/* @var $model AboutModel */
/* @var $view AboutView */

?>

<div id="main_wrap">

    <div class="ineer_wrap">

        <div class="sidebar">

            <a href="/park/focus" class="button active">Отраслевой фокус</a>
            <a href="/park/news" class="button">Новости</a>
            <a href="/park/partners" class="button">Партнеры</a>

        </div>

        <div id="main_text" class="inner_content">

            <hr>

            <h3>Отраслевой фокус</h3>

            <div class="focus_list">
                <img src="/prod_src/img/swipper/img_0.jpg">
                <p>Глубокая переработка ТКО</p>
                <div class="clear"></div>
            </div>

            <div class="focus_list">
                <img src="/prod_src/img/swipper/img_1.jpg">
                <p>Создание тепличных комплексов</p>
                <div class="clear"></div>
            </div>

            <div class="focus_list">
                <img src="/prod_src/img/swipper/img_2.jpg">
                <p>Создание металлургических комплексов</p>
                <div class="clear"></div>
            </div>

            <div class="focus_list">
                <img src="/prod_src/img/swipper/img_4.jpg">
                <p>Производство немагнитных утяжеленных бурильных и ведущих труб</p>
                <div class="clear"></div>
            </div>

            <div class="focus_list">
                <img src="/prod_src/img/swipper/img_5.jpg">
                <p>Производство твердых сплавов и инструмента</p>
                <div class="clear"></div>
            </div>

            <div class="focus_list">
                <img src="/prod_src/img/swipper/img_3.jpg">
                <p>Производство геофизического оборудования</p>
                <div class="clear"></div>
            </div>

            <hr>

        </div>

    </div>
</div>