<?php

/* @var $model AboutModel */
/* @var $view AboutView */

?>

<div id="main_wrap">

    <div class="ineer_wrap">

        <div class="sidebar">

            <a href="/park/focus" class="button">Отраслевой фокус</a>
            <a href="/park/news" class="button active">Новости</a>
            <a href="/park/partners" class="button">Партнеры</a>

        </div>

        <div id="main_text" class="inner_content">

            <hr>

            <p class="content_missing">
                Сайт находится на наполнении
            </p>

            <hr>

        </div>

    </div>
</div>