<?php

/* @var $model AboutModel */
/* @var $view AboutView */

?>

<div id="main_wrap">

    <div class="ineer_wrap">

        <div class="sidebar">

            <a href="/park/focus" class="button">Отраслевой фокус</a>
            <a href="/park/news" class="button">Новости</a>
            <a href="/park/partners" class="button">Партнеры</a>

        </div>

        <div id="main_text" class="inner_content">

            <hr>

            <b style="font-size:22px;">Концепция индустриального парка основывается на:</b>

            <ul class="list">
                <li>
                    комплексном подходе к решению проблемы утилизации твердых коммунальных отходов, образующихся в г. Уфа,
                    Уфимском и Иглинском районах РБ, с последующей выработкой электрической и тепловой энергии
                </li>
                <li>
                    размещении энергоемких производств в рамках вертикально-интегрированной производственной цепочки
                    на территории парка позволит обеспечить гарантированный спрос на энергию, генерируемую ТКО
                </li>
            </ul>

            <hr>

        </div>

    </div>
</div>