<?php
/**
 * шапка шаблона
 * @var CommonView $common_view
 */
$common_view = Application::$common_view;
?>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/Swiper/4.4.6/css/swiper.css">
    <link rel="stylesheet" type="text/css" href="/public/prod_src/css/common.css">
    <link rel="shortcut icon" href="/public/prod_src/img/favicon.png" type="image/x-icon">

    <?php

    switch (Application::$application_name) {

        case 'Page404':
            echo '<link rel="stylesheet" type="text/css" href="/public/prod_src/css/page404.css">';
            break;

        default:
            echo '<link rel="stylesheet" type="text/css" href="/public/prod_src/css/home.css">';

    }

    ?>

</head>