<?php
/**
 * шапка шаблона
 * @var CommonView $common_view
 */
$common_view = Application::$common_view;
?>
<head>
    <title><?php echo CommonSEOHelper::$title; ?></title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <meta name="description" content="<?php echo CommonSEOHelper::$description; ?>"/>
    <meta name="keywords" content="<?php echo CommonSEOHelper::$keywords; ?>"/>
    <meta name="robots" content="<?php echo CommonSEOHelper::$robots; ?>"/>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/Swiper/4.4.6/css/swiper.css">

    <link rel="stylesheet" type="text/css" href="/prod_src/css/common.css">


    <?php

    switch (Application::$application_name) {

        case 'Discounts':
            echo '<link rel="stylesheet" type="text/css" href="/prod_src/css/discounts.css">';
            break;

        case 'Stories':
            echo '<link rel="stylesheet" type="text/css" href="/prod_src/css/stories.css">';
            break;

        case 'Page404':
            echo '<link rel="stylesheet" type="text/css" href="/prod_src/css/page404.css">';
            break;

        default:
            echo '<link rel="stylesheet" type="text/css" href="/prod_src/css/home.css">';

    }

    ?>

</head>