<?php
/* @var $model DiscountsModel */
/* @var $view DiscountsView */
?>

<div id="popup" class="<?php echo($view->is_popup ? 'discountPopup' : 'discountPage'); ?>">
    <div id="popupContainerWithArrows" class="<?php echo($view->is_popup ? 'popupWindow' : 'popupPage'); ?>">
        <?php if ($view->is_popup) { ?>
            <div class="popupContainerNav">
            <span class="logoImgCont">
                <svg width="801px" height="30px" viewbox="0 0 801 221" version="1.1">
                    <defs></defs>
                    <g id="Page-1" stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
                        <g id="Group" fill="#9F9F9F">
                            <polygon id="Rectangle"
                                     points="274 0 523 0 523 221 453.938477 221 453.938477 55 342.991211 55 342.991211 221 274 221"></polygon>
                            <path id="Rectangle"
                                  d="M731,95 L731,70 C731,70 731.122348,66.985529 730,64.5 C729.841533,64.1490628 729.686142,63.8232701 729.530743,63.5174787 C728.288587,60.929463 726.325795,58.752955 723.902407,57.2479948 C723.116155,56.7014641 722.408829,56.3633542 721.5,56 C721.250019,55.9000563 720.945218,55.8070648 720.608607,55.7212723 C719.156574,55.2529672 717.607829,55 716,55 C715.998375,55 715.99675,55.0000003 715.995126,55.0000008 C715.995119,55.0000001 715.995117,55 715.995117,55 L619.991211,55 C619.991211,55 619.991211,91.1728516 619.991211,110 C619.991211,128.827148 619.991211,221 619.991211,221 L551,221 L551,7.10542736e-15 L753,7.10542736e-15 L740,41.5 L800,49.5888672 L800,121.662109 L738.5,110.5 L753,165 L619.991211,165 L619.991211,110 L716,110 C724.284271,110 731,103.284271 731,95 Z"></path>
                            <path id="Oval"
                                  d="M800.098633,165 L800.098633,110 L776,110 C751.147186,110 731,130.147186 731,155 L731,165 L800.098633,165 Z"
                                  transform="translate(765.549316, 137.500000) scale(-1, -1) translate(-765.549316, -137.500000) "></path>
                            <path id="Oval"
                                  d="M800.098633,55 L800.098633,0 L776,0 C751.147186,0 731,20.1471863 731,45 L731,55 L800.098633,55 Z"
                                  transform="translate(765.549316, 27.500000) scale(-1, 1) translate(-765.549316, -27.500000) "></path>
                            <path id="Rectangle"
                                  d="M84.0268555,165 L165.055786,165 C172.977936,164.971057 179.452637,158.800856 179.967055,151.002125 L180,151 L180,144 L249,144 L249,166 L209,189 L200,221 L45.6225586,221 L38.5,194.5 L0,177 L0,48.8813477 L45.6225586,-3.78653235e-29 L206.858398,-3.78653235e-29 L206.858398,36.5 L249,43.5 L249,77 L180,77 L180,70 C180,61.7157288 173.284271,55 165,55 L84.4599609,55 L84.4535905,55.0067272 C84.3029377,55.0022529 84.1517319,55 84,55 C75.7157288,55 69,61.7157288 69,70 C69,70.4276214 69.0178938,70.8510634 69.0529736,71.2696182 L68.9912109,71.3348389 L68.9912109,150.02478 L69.0000368,150.033571 C69.0181504,158.302407 75.7269218,165 84,165 C84.0089458,165 84.0178898,164.999992 84.0268319,164.999977 Z"></path>
                            <path id="Oval"
                                  d="M69.0986328,55 L69.0986328,0 L45,0 C20.1471863,0 0,20.1471863 0,45 L0,55 L69.0986328,55 Z"></path>
                            <path id="Oval"
                                  d="M69.0986328,221 L69.0986328,166 L45,166 C20.1471863,166 0,186.147186 0,211 L0,221 L69.0986328,221 Z"
                                  transform="translate(34.549316, 193.500000) scale(1, -1) translate(-34.549316, -193.500000) "></path>
                            <path id="Oval"
                                  d="M249.098633,221 L249.098633,166 L225,166 C200.147186,166 180,186.147186 180,211 L180,221 L249.098633,221 Z"
                                  transform="translate(214.549316, 193.500000) scale(-1, -1) translate(-214.549316, -193.500000) "></path>
                            <path id="Oval"
                                  d="M249.098633,55 L249.098633,0 L225,0 C200.147186,0 180,20.1471863 180,45 L180,55 L249.098633,55 Z"
                                  transform="translate(214.549316, 27.500000) scale(-1, 1) translate(-214.549316, -27.500000) "></path>
                        </g>
                    </g>
                </svg>
                </span>
                <span class="closePopupImg">
                    <img src="/prod_src/img/firms/popup/cansel.png" id="closePopupImg" width="20" height="20" alt="">
                </span>
            </div>
        <?php } ?>
        <div id="popupContentWithArrows">

            <?php if ($model->discount_data['prev_id'] > 0) { ?>
                <a class="left" href="<?php echo $model->discount_data['prev_link']; ?>">
                    <img src="<?php echo($view->is_popup ? '/prod_src/img/firms/popup/left.png' : '/prod_src/img/firms/popup/left-dark.png'); ?>"
                         width="11" height="18" alt=""/>
                </a>
            <?php } ?>

            <div class="popupContainer">
                <div class="popupContent" id="popupContent">
                    <?php if (!$view->is_popup) { ?>
                        <div class='popupContentTextHeader mobHeader'>
                            <div class="popupContentTextHeaderMain">
                                <?php if (!empty($model->net_data['logo_net'])) { ?>
                                    <div class="popupContentTextHeaderImg">
                                        <a href="">
                                            <img src="<?php echo $model->net_data['logo_net']; ?>" alt=""/>
                                        </a>
                                    </div>
                                <?php } ?>
                                <div class="popupContentTextHeaderText">
                                    <h3>
                                        <a href="<?php echo $model->net_data['division_url']; ?>">
                                            <?php echo $model->net_data['name_net']; ?>
                                        </a>
                                    </h3>
                                    <div class="allDiscounts">
                                        <a href="<?php echo $model->net_data['discounts_url']; ?>">
                                            Все скидки и акции организации</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    <?php } ?>

                    <div class="popupContentMainImg">
                        <div style="background:url(<?php echo $model->discount_data['image_url']; ?>)"></div>
                    </div>

                    <div class="popupContentText">
                        <div class="popupContentTextMainText" id="popupContentTextMainText">
                            <?php if (!$view->is_popup) { ?>
                                <div class="popupContentTextHeader">
                                    <div class="popupContentTextHeaderMain">
                                        <div class="popupContentTextHeaderText">
                                            <h3>
                                                <a href="<?php echo $model->net_data['division_url']; ?>">
                                                    <?php echo $model->net_data['name_net']; ?>
                                                </a>
                                            </h3>
                                            <div class="allDiscounts">
                                                <a href="<?php echo $model->net_data['discounts_url']; ?>">
                                                    Все скидки и акции организации</a>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            <?php } else { ?>
                                <div class='popupContentTextHeader'>
                                    <h3><?php echo $model->discount_data['heading']; ?></h3>
                                </div>
                            <?php } ?>
                            <?php if (!$view->is_popup) { ?>
                                <h4><?php echo $model->discount_data['heading']; ?></h4>
                            <?php } ?>

                            <p class="period_discount">
                                <?php if (!!$model->discount_data['before_end']) { ?>
                                    <?php if (isset($model->discount_data['today_end'])) { ?>
                                        <span>Акция сегодня заканчивается!</span>
                                    <?php } else { ?>
                                        <span>До завершения осталось:
                                        <br/>
                                            <?php echo $model->discount_data['before_end']; ?>
                                        </span>
                                    <?php } ?>
                                <?php } else { ?>
                                    <span><b>Акция закончилась</b></span>
                                <?php } ?>
                            </p>

                            <?php if ($model->discount_data['active'] && $model->filials_data['has_data']) { ?>
                                <p>
                                    <b>Акция действует в таких филиалах:</b>
                                </p>
                            <?php } ?>

                            <?php if ($model->discount_data['active'] && $model->filials_data['has_data']) { ?>
                                <div class="containerPriceSubsidiary filials_data_wrapper">
                                    <div class="filials_data">
                                        <?php foreach ($model->filials_data['data'] as $discount_filial) { ?>
                                            <div class="priceSubsidiary <?php echo $discount_filial['css_class'] ?? 'hide'; ?>">
                                                <div class="subsidiary">
                                                    <span class="link">
                                                        <a href="<?php echo $discount_filial['firm_discount_url']; ?>">
                                                            <?php echo $discount_filial['address_firm']; ?>
                                                        </a>
                                                    </span>
                                                    <div class="price">
                                                        <?php if ($discount_filial['percent_original']) { ?>
                                                            <div class="discountsPercent">
                                                                <span class="beforePrice">Выгода:</span>
                                                                <?php echo $discount_filial['percent_original']; ?>
                                                                %
                                                            </div>
                                                        <?php } ?>
                                                    </div>
                                                </div>
                                                <div class="sheetElement">
                                                    <a href="<?php echo $discount_filial['firm_discount_url']; ?>"
                                                       class="btn-normal btn-white fix-btn" title="Перейти">
                                                        <img src="/prod_src/img/firms/division/arrow-right-bold.png"
                                                             width="10" height="18" alt=""/>
                                                    </a>
                                                </div>
                                            </div>
                                        <?php } ?>
                                    </div>

                                    <?php if ($model->filials_data['has_more']) { ?>
                                        <div title="<?php echo $model->filials_data['show_all_title']; ?>"
                                             class="allPrices under_net">
                                            <a class="show_all_filials">Показать все филиалы</a>
                                        </div>
                                    <?php } ?>

                                </div>
                            <?php } ?>

                            <div class="popupContentTextMainTextButton">
                                <?php if ($model->discount_data['button_text']) { ?>
                                    <a class="popupContentTextMainTextLink actionBtn"
                                       href="<?php echo $model->discount_data['url_skidki']; ?>"
                                       onclick="return discounts.sendClickLog(<?php echo $model->discount_data['id']; ?>);"
                                       rel="nofollow"
                                       target="_blank">
                                        <span><?php echo $model->discount_data['button_text']; ?></span>
                                        <img src="/prod_src/img/firms/opinions/arrow-point-to-right.png" width="7px"
                                             height="12px" id="footerArr" alt=""/>
                                    </a>

                                <?php } ?>
                            </div>

                            <p id='last_paragraph'><?php echo $model->discount_data['preview']; ?></p>
                            <p></p>
                        </div>
                        <div class="popupContentTextWhatToDo">
                            <div class="whatToDo">
                                <div class="doIt">
                                    <p>Поделиться:</p>
                                    <div class="whatToDoPictures">
                                        <a href="https://www.facebook.com/sharer/sharer.php?u=<?php echo $model->discount_data['popup_link_share']; ?>"
                                           class="fbbtn" target="_blank">
                                            <img src="/prod_src/img/firms/popup/fb.png"
                                                 alt=""/>
                                        </a>
                                        <a href="http://vk.com/share.php?url=<?php echo $model->discount_data['popup_link_share']; ?>"
                                           target="_blank">
                                            <img src="/prod_src/img/firms/popup/vk.png"
                                                 alt=""/>
                                        </a>
                                    </div>
                                </div>
                            </div>
                            <div class="oveflowTextWrapp"></div>
                        </div>
                    </div>
                </div>
            </div>

            <?php if ($model->discount_data['next_id'] > 0) { ?>
                <a class="right" href="<?php echo $model->discount_data['next_link']; ?>">
                    <img src="<?php echo($view->is_popup ? '/prod_src/img/firms/popup/right.png' : '/prod_src/img/firms/popup/right-dark.png'); ?>"
                         width="11" height="18" alt=""/>
                </a>
            <?php } ?>
        </div>
    </div>
</div>

<section class="advertBlock bottom-block bottom-150">
    <!-- Yandex.RTB R-A-116199-1 -->
    <div id="yandex_rtb_R-A-116199-1"></div>
    <script type="text/javascript" src="//an.yandex.ru/system/context.js" async=""></script>
    <script type="text/javascript">
        (function(w, d, n, s, t) {
            w[n] = w[n] || [];
            w[n].push(function() {
                Ya.Context.AdvManager.render({
                    blockId: "R-A-116199-1",
                    renderTo: "yandex_rtb_R-A-116199-1",
                    async: true
                });
            });
            t = d.getElementsByTagName("script")[0];
            s = d.createElement("script");
            s.type = "text/javascript";
            s.src = "//an.yandex.ru/system/context.js";
            s.async = true;
            t.parentNode.insertBefore(s, t);
        })(this, this.document, "yandexContextAsyncCallbacks");
    </script>
</section>