<?php
/* @var $model SocialModuleModel */
/* @var $view SocialModuleView */
$current_url = Application::$base_domain;
$uri = trim($_SERVER['REQUEST_URI'], '/');
if ($uri) {
    $current_url .= $uri;
}
$current_url_encoded = urlencode($current_url);
?>

<div id="share_target" class="social-fixed-menu flex-column-center">
    <span class="med-14"><?php echo $model->click_count['count'] ?></span>
    <span class="mini grey">подели-лось</span>
    <a id="vk" target="_blank"
       href="http://vk.com/share.php?url=<?php echo $current_url_encoded; ?>"
       class="vk soc">
        <img src="/prod_src/img/firms/modules/soc_ntw/vk.png" width="19" height="11" alt="">
        <span><?php echo $model->click_count['vk'] ?></span>
    </a>
    <a id="ok" target="_blank"
       href="https://connect.ok.ru/dk?st.cmd=WidgetSharePreview&st.shareUrl=<?php echo $current_url_encoded; ?>"
       class="ok soc">
        <img src="/prod_src/img/firms/modules/soc_ntw/ok.png" width="9" height="15" alt="">
        <span><?php echo $model->click_count['ok'] ?></span>
    </a>
    <a id="fb" target="_blank"
       href="https://www.facebook.com/sharer.php?s=100&p[url]=<?php echo $current_url_encoded; ?>"
       class="fb soc">
        <img src="/prod_src/img/firms/modules/soc_ntw/fb.png" width="7" height="13" alt="">
        <span><?php echo $model->click_count['fb'] ?></span>
    </a>
    <a id="gp" target="_blank" href="https://plus.google.com/share?url=<?php echo $current_url_encoded; ?>" class="g soc">
        <img src="/prod_src/img/firms/modules/soc_ntw/g+.png" width="13" height="11" alt="">
        <span><?php echo $model->click_count['gp'] ?></span>
    </a>
    <a id="pop1" class="watch_all">
        <img src="/prod_src/img/firms/modules/soc_ntw/pop1.png" width="23" height="4" alt="">
    </a>
    <a id="pop2" class="arrow_cherry top-30">
        <img src="/prod_src/img/firms/modules/soc_ntw/pop2.png" width="15" height="14" alt="">
    </a>
</div>

<div class="b-popup flex-row-end-center" id="popup_info" style="display: none;">
    <div class="b-popup-info">
        <p class="reg-15 grey bottom-20">
            <?php echo $model->confirmed_date_text ?>&nbsp;<?php echo $model->confirmed_date ?>
        </p>

        <a href="<?php echo $model->checkcorrect_url ?>" class="reg-15 h-blue">Заметили ошибку?</a>

        <div class="line top-20"></div>

        <?php
        $forum_adding_url = Application::$base_domain . 'forum_adding.php?id_top=11&id_firm_forum=' . $model->getOrganizationData('id');
        ?>
        <a href="<?php echo $forum_adding_url ?>" class="reg-15 h-blue top-20">Добавить отзыв</a>

        <div class="line top-20"></div>

        <a href="<?php echo $model->cabinet_url ?>" class="reg-15 h-blue top-20">Войти в кабинет организации</a>

        <a href="<?php echo $model->statistics_url; ?>" class="reg-15 h-blue top-20">Смотреть статистику</a>

        <a href="<?php echo $model->business_url ?>" class="reg-15 h-blue dsp-block top-20">Дать рекламу</a>

        <a class="cansel">
            <img src="/prod_src/img/firms/modules/soc_ntw/cansel_popup.png" width="16" height="15" alt="">
        </a>
    </div>
</div>