<?php
/** @var CommonModel $common_model */
$common_model = Application::$common_model;
?>

<section class="footer">
    <div class="footerWrap">

        <div class="footerMenu">
            <div class="footerMenuBlock">
                <span class="footerMenuBlockName">О компании</span>

                <div class="footerMenuBlockPages">

                    <a href="/about/mission">Наша миссия</a>
                    <a href="/about/contacts">Контакты</a>
                    <a href="/about/production">Продукция и услуги</a>
                    <a href="/about/feedback">Написать нам</a>

                </div>
            </div>
            <div style="display:none" class="footerMenuBlock">
                <span class="footerMenuBlockName">Экотехнопарк</span>

                <div class="footerMenuBlockPages">

                    <a href="/park/focus">Отраслевой фокус</a>
                    <a href="/park/news">Новости</a>
                    <a href="/park/partners">Партнеры</a>

                </div>
            </div>
            <div class="footerMenuBlock">
                <span class="footerMenuBlockName">Документация</span>

                <div class="footerMenuBlockPages">

                    <a href="/documents/foundation">Учредительные документы</a>
                    <a href="/documents/presentations">Презентации</a>

                </div>
            </div>

            <div class="footerMenuBlock">
                <span class="footerMenuBlockName"></span>

                <div class="footerMenuBlockPages">

                    <a href="/public/sitemap.xml">Карта сайта</a>

                </div>
            </div>

        </div>

        <div class="footerButtonBlock">
        </div>

        <div class="footerCopyright">

            <div class="copyrightTextContainer">
                <span class="footerCopyrightIcon"></span>
                <span class="footerCopyrightText">ООО «ГеоРостГрупп»</span>
                <span class="footerCopyrightText">2018 &mdash; <?php echo date('Y'); ?></span>
            </div>

        </div>
    </div>
</section>