<?php
/** @var CommonModel $common_model */
$common_model = Application::$common_model;
?>
<section>
    <script src='/prod_src/alone_js/libs/jquery-3.3.1.min.js'></script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/Swiper/4.4.6/js/swiper.js"></script>

    <script src='/prod_src/js/common/common.js'></script>

    <?php

    switch (Application::$application_name) {

        case 'Discounts':
            echo '<script type="text/javascript" src="/prod_src/js/discounts.js" charset="utf-8"></script>';
            break;

        case 'Page404':
            echo '<script type="text/javascript" src="/prod_src/js/page404.js" charset="utf-8"></script>';
            break;

        case 'Home':
        default:
            echo '<script type="text/javascript" src="/prod_src/js/home.js" charset="utf-8"></script>';
            break;
    }
    ?>

    <script src="/prod_src/js/_modules/swiper_text.js"></script>

</section>