<?php

/* @var $model HomeModel */
/* @var $view HomeView */

?>

<div id="main_wrap">

    <div class="swiper-container">

        <div class="swiper-wrapper">
            <div class="swiper-slide"><img src="/public/prod_src/img/swipper/img_2.jpg"></div>
            <div class="swiper-slide"><img src="/public/prod_src/img/swipper/img_3.jpg"></div>
            <div class="swiper-slide"><img src="/public/prod_src/img/swipper/img_4.jpg"></div>
            <div class="swiper-slide"><img src="/public/prod_src/img/swipper/img_5.jpg"></div>
            <div class="swiper-slide"><img src="/public/prod_src/img/swipper/img_1.jpg"></div>
            <div class="swiper-slide"><img src="/public/prod_src/img/swipper/img_0.jpg"></div>
        </div>

        <div class="swiper-pagination"></div>

        <div class="swiper-button-prev"></div>
        <div class="swiper-button-next"></div>

        <div class="swiper-scrollbar"></div>

        <div class="swiper-text">

        </div>

    </div>

    <hr>

    <div id="home_intro">
        <p>
            ООО «ГеоРостГрупп» - инновационная компания, зарегистрированная в Республике Башкортостан в 2018 году.
            Цели компании: создание и эксплуатация уникальных производств в сфере глубокой переработки промышленных отходов,
            металлургии, производства твердых сплавов и твердосплавного инструмента, геофизического оборудования и информационных технологий.
        </p>
        <p>
            В основе деятельности ООО «ГеоРостГрупп» лежит изучение новейших отечественных и зарубежных технологий, НОУ-ХАУ для формирования и реализации инвестиционных проектов.
            Разработка и структурирование проектов осуществляется при непосредственном участии разработчиков технологий и при обязательном авторском надзоре и
            научно-технологическом сопровождении технологическими партнерами на всех стадиях подготовки и реализации проекта.
        </p>
        <p>
            Создание масштабируемого проекта позволяет реализовывать его на всей территории России.
            Финансовая модель инвестиционного проекта предполагает использование собственных средств инициатора проекта,
            а также средств институциональных инвесторов и использование механизмов государственно-частного партнерства в
            соответствии с Федеральным законом от 13 июля 2015 года №224-ФЗ.
        </p>
        <p>
            Технологическими партнерами компании являются проектные, научно-исследовательские и производственные организации Москвы, Санкт-Петербурга, Новосибирска, Уфы, Ижевска.
        </p>
    </div>


</div>

<div id="modal_win">
    <div id="modal_win_content"></div>
</div>