<?php

/* @var $model HomeModel */
/* @var $view HomeView */

?>

<div id="main_wrap">

    <div class="swiper-container">

        <div class="swiper-wrapper">
            <div class="swiper-slide"><img src="/prod_src/img/swipper/img_1.jpg"></div>
            <div class="swiper-slide"><img src="/prod_src/img/swipper/img_2.jpg"></div>
            <div class="swiper-slide"><img src="/prod_src/img/swipper/img_3.jpg"></div>
            <div class="swiper-slide"><img src="/prod_src/img/swipper/img_4.jpg"></div>
            <div class="swiper-slide"><img src="/prod_src/img/swipper/img_5.jpg"></div>
            <div class="swiper-slide"><img src="/prod_src/img/swipper/img_0.jpg"></div>
        </div>

        <div class="swiper-pagination"></div>

        <div class="swiper-button-prev"></div>
        <div class="swiper-button-next"></div>

        <div class="swiper-scrollbar"></div>

        <div class="swiper-text">

        </div>

    </div>

    <hr>

    <div id="home_intro">

        <p>
            ООО «ГеоРостГрупп» &mdash; инновационная компания, созданная для внедрения передовых технологий в сфере металлургии,
            производства геофизического оборудования, твердосплавного инструмента и переработки твердых коммунальных отходов.
        </p>

        <p>
            Компания зарегистрирована в 2018 году в Иглинском районе Республики Башкортостан.
        </p>

        <p>
            В основе деятельности ООО «ГеоРостГрупп» лежит изучение новейших отечественных и зарубежных технологий для формирования и
            реализации инвестиционных проектов на территории Российской Федерации.
            <br>
            Реализуемая финансовая модель предполагает использование средств институциональных инвесторов и исользование механизмов
            частно-государственного партнерства.
        </p>

        <p>
            Партнерами ООО «ГеоРостГрупп» являются проектные, научно-исследовательские и производственные организации.
            <br>
            Среди технологических партнеров – крупнейшие научные центры Уфы, Москвы, Санкт-Петербурга, Новосибирска.
        </p>

    </div>

    <hr>

    <h2>Новости компании</h2>

    <p class="content_missing">
        Сайт находится на наполнении
    </p>

    <hr>

    <h2>Партнеры</h2>

    <p class="content_missing">
        Сайт находится на наполнении
    </p>

    <hr>

</div>

<div id="modal_win">
    <div id="modal_win_content"></div>
</div>